name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
      - name: Run unit tests
        run: npm install && npm test


